
server:
  port: 5000

spring:
  application:
    title: Application gateway
    version: 1.0
    name: gateway


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

      routes:
        - id: user-service
          uri: http://localhost:3500
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /v1.0/invoke/user-service/method/$\{segment}
        - id: message-service
          uri: http://localhost:3500
          predicates:
            - Path=/message/**
          filters:
            - RewritePath=/message/(?<segment>.*), /v1.0/invoke/message-service/method/$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
          audiences: ${AUDIENCE_USER_SERVICE}, ${AUDIENCE_MESSAGE_SERVICE}
