application:
  title: Message Service
  version: 1.0


server:
  port: 5002

spring:
  jpa:
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: ${CONNECTION_STRING}
      database: ${DB_NAME_MESSAGE}
      auto-index-creation: true

