application:
  title: Message Service
  version: 1.0


server:
  port: 5002

spring:
  jpa:
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: ${CONNECTION_STRING}
      database: ${DB_NAME_MESSAGE}
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
          audiences: ${AUDIENCE_MESSAGE_SERVICE}

