# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & test services

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache.
          key: ${{ runner.os }}-m2-${{ hashFiles('gateway/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-

      - name: Build with Maven
        run: mvn -B package --file gateway/pom.xml

  user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # If the hash of the project files is the same, use cache.
          key: ${{ runner.os }}-m2-${{ hashFiles('services/user-service/pom.xml') }}
          restore-keys: ${{ runner.os}}-m2-

      - name: Build with Maven
        run: mvn -B package --file services/user-service/pom.xml

  message-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        # If the hash of the project files is the same, use cache.
        key: ${{ runner.os }}-m2-${{ hashFiles('services/message-service/pom.xml') }}
        restore-keys: ${{ runner.os}}-m2-
    - name: Build with Maven
      run: mvn -B package --file services/message-service/pom.xml
      
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results.sarif
        # # Optional: Specify the Kubescape cloud account ID
        # account: ${{secrets.KUBESCAPE_ACCOUNT}}
        # # Optional: Scan a specific path. Default will scan the whole repository
        # files: "examples/*.yaml"
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
