# Builds and push images to GitHub container registry

name: 'Build & deploy images'

on:
  push:
    branches: [ master ]


env:
  REGISTRY: ghcr.io
  GATEWAY_TAG_PUSH: ghcr.io/piet2001/kwetter-gateway:${{ github.sha }}
  USER_TAG_PUSH: ghcr.io/piet2001/kwetter-user-service:${{ github.sha }}
  MESSAGE_TAG_PUSH: ghcr.io/piet2001/kwetter-message-service:${{ github.sha }}

jobs:

  build_push_images:

    runs-on: ubuntu-latest
    name: Builds and pushes images

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: mvn clean package

      - name: Build & push gateway
        uses: docker/build-push-action@v2
        with:
          context: gateway
          push: true
          tags: ${{ env.GATEWAY_TAG_PUSH }}

      - name: Build & push user
        uses: docker/build-push-action@v2
        with:
          context: services/user-service
          push: true
          tags: ${{ env.USER_TAG_PUSH }}

      - name: Build & push message
        uses: docker/build-push-action@v2
        with:
          context: services/message-service
          push: true
          tags: ${{ env.MESSAGE_TAG_PUSH }}
